ignorePatterns:
  - "**/dist/**/*"
env:
  es2021: true
  "jest/globals": true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'jest'
rules:
  curly: "error"
  comma-dangle: [ "warn", "never" ]
  "jest/no-disabled-tests": "warn"
  "jest/no-focused-tests": "error"
  "jest/no-identical-title": "error"
  "jest/prefer-to-have-length": "warn"
  "jest/valid-expect": "error"
  "@typescript-eslint/no-explicit-any": "off"
root: true
