name: Deploy to cluster
on: [ push ]
jobs:
  TestedJob:
    name: "Deploy facsimile"
    runs-on: docker.home.arpa/venthe/ubuntu-runner:22.10
    steps:
      - uses: actions/checkout@main
      - uses: .pipeline/actions

